name: Auto Update Postman Collections

on:
  push:
    branches:
    - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Sync Postman Collections
      uses: jneate/postman-collection-action@v1
      with:
        postmanApiKey: ${{ secrets.postmanApiKey }}
        postmanWorkspaceId: 803eebb5-81bb-4330-957d-75c3e0cc0454
        postmanTimeout: 60000